#pragma once

typedef struct
{
	LARGE_INTEGER physicalAddress;
	ULONG accessCount;
} PHYSICAL_ADDRESS_ACCESS_REQUEST, * PPHYSICAL_ADDRESS_ACCESS_REQUEST;

#define PHYSICAL_ADDRESS_ACCESS_DEVICE 0x8000
#define READ_FUNCTION_CODE 0x800
#define WRITE_FUNCTION_CODE 0x801
#define IOCTL_PHYSICALADDRESS_READ CTL_CODE(PHYSICAL_ADDRESS_ACCESS_DEVICE, READ_FUNCTION_CODE, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PHYSICALADDRESS_WRITE CTL_CODE(PHYSICAL_ADDRESS_ACCESS_DEVICE, WRITE_FUNCTION_CODE, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)