#pragma once

//
// Define an Interface Guid for toaster device class.
// This GUID is used to register (IoRegisterDeviceInterface)
// an instance of an interface so that user application
// can control the toaster device.
//
//DEFINE_GUID(GUID_DEVINTERFACE_ECIO,0x981EF630, 0x72B2, 0x11d2, 0xB8, 0x52, 0x00, 0xC0, 0x4F, 0xAD, 0x61, 0x71);
//{981EF630-72B2-11d2-B852-00C04FAD6171}

typedef struct {
    LARGE_INTEGER physicalAddress;
    ULONG accessCount;
} PHYSICAL_ADDRESS_ACCESS_REQUEST, * PPHYSICAL_ADDRESS_ACCESS_REQUEST;

#define PHYSICAL_ADDRESS_ACCESS_DEVICE 0x8000
#define READ_FUNCTION_CODE 0x800
#define WRITE_FUNCTION_CODE 0x801
#define IOCTL_PHYSICALADDRESS_READ CTL_CODE(PHYSICAL_ADDRESS_ACCESS_DEVICE, READ_FUNCTION_CODE, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PHYSICALADDRESS_WRITE CTL_CODE(PHYSICAL_ADDRESS_ACCESS_DEVICE, WRITE_FUNCTION_CODE, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

